import { z } from "zod";

export const validation = z.object({
  gestanteId: z.number(),
  municipio: z.string(),
  diagnostico_desnutricao: z.boolean(),
  energia_eletrica_domicilio: z.boolean(),
  escolaridade: z.number(),
  tipo_moradia: z.number(),
  moradia_rede_esgoto: z.boolean(),
  renda_familiar: z.number(),
  tratamento_agua: z.boolean(),
  amamentacao: z.boolean(),
  chefe_familia: z.boolean(),
  data_ultima_amamentacao: z.date(),
  em_risco: z.boolean(),
  estado_civil: z.number(),
  quantidade_abortos: z.number(),
  quantidade_filhos_vivos: z.number(),
  quantidade_gemelares: z.number(),
  quantidade_gestacao: z.number(),
  quantidade_nascidos_mortos: z.number(),
  quantidade_nascidos_vivos: z.number(),
  quantidade_obitos_semanal: z.number(),
  quantidade_obitos_apos_semanal: z.number(),
  quantidade_partos: z.number(),
  quantidade_partos_cesarios: z.number(),
  quantidade_partos_vaginais: z.number(),
  quantidade_rn_peso2500_4000: z.number(),
  quantidade_rn_peso_maior4000: z.number(),
  quantidade_rn_peso_menor2500: z.number(),
  hipertensao: z.boolean(),
  diabetes: z.boolean(),
  cirurgia_pelvica: z.boolean(),
  infeccao_urinaria: z.boolean(),
  ma_formacao_congenita: z.boolean(),
  contato: z.string(),
  contato_emergencia: z.string(),
  data_atualizacao: z.date(),
});
